info:
  version: 1.0.0
  description: NF initial local configuration

configuration:
  nfName: NF # the name of this NF
  sbi: # Service-based interface information
    scheme: http # the protocol for sbi (http or https)
    bindingIPv4: 127.0.0.163  # IP used to bind the service
    port: 8000 # Port used to bind the service
    tls: # the local path of TLS key
      pem: cert/nf.pem # NF TLS Certificate
      key: cert/nf.key # NF TLS Private key

logger: # log output setting
  enable: true # true or false
  level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  reportCaller: false # enable the caller report or not, value: true or false